#http://guides.cocoapods.org/using/the-podfile.html
platform :ios, '8.0'
inhibit_all_warnings!

target 'Alpaca' do
 pod 'YYText'
 pod 'YYImage'
 pod 'Masonry'
 pod 'MJRefresh'
 pod 'MJExtension'
 pod 'Toast'
 pod 'YTKNetwork'
 # 集成微信(精简版0.2M)
 pod 'UMCShare/Social/ReducedWeChat'
 # 集成QQ/QZone/TIM(精简版0.5M)
 pod 'UMCShare/Social/ReducedQQ'
 # 集成新浪微博(精简版1M)
 pod 'UMCShare/Social/ReducedSina'
 # 友盟统计
 pod 'UMCAnalytics'
 pod 'SDWebImage'
 pod 'TYAttributedLabel'
 pod 'MBProgressHUD'
 pod 'UITableView+FDTemplateLayoutCell'
 pod 'SGAdvertScrollView'
 pod 'JPush'



  target 'AlpacaTests' do
    inherit! :search_paths
   
  end

  target 'AlpacaUITests' do
    inherit! :search_paths
    
  end

end
